version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map port 80 in the container to port 8080 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=172.18.0.2;Database=new_sc;User=vijaylaxmi;Password=password;
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vijaylaxmi
      MYSQL_DATABASE: new_sc
    ports:
      - "3306:3306" # Expose MySQL on port 3306
    volumes:
      - db_data:/var/lib/mysql   
     
volumes:
  db_data:
